-- liquibase formatted sql

-- changeset Alex:1
CREATE TABLE book
(
    name      TEXT NOT NULL,
    author_id INTEGER
);

CREATE TABLE author
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

-- changeset Alex:2
SELECT author.name, book.name
FROM author
         JOIN book
                    ON author.id = book.author_id
WHERE author.id = 1;